version: "3.5"
services:
  nginx:
    build: ./requirements/nginx
    container_name : nginx
    volumes:
      - wp-website:/var/www/html/wordpress
    image: inception/nginx
    ports:
      - "443:443"
    networks:
      - inception

  mariadb:
    build: 
      context: ./requirements/mariadb
      args:
        DBNAME : ${DBNAME}
        USERNAME : ${USERNAME}
        PASSWORD : ${PASSWORD}
    container_name : mariadb
    volumes:
      - wp-database:/var/lib/mysql
    image: inception/mariadb
    networks:
      - inception

  wordpress:
    build: 
      context: ./requirements/wordpress
      args:
        DBNAME : ${DBNAME}
        USERNAME : ${USERNAME}
        PASSWORD : ${PASSWORD}
    container_name : wordpress
    volumes:
      - wp-website:/var/www/html/wordpress
    image: inception/wordpress
    networks:
      - inception
  
networks:
  inception:
    driver: bridge

volumes:
  wp-database:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/mysql

  wp-website:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/wp
