version: "3.5"
services:
  nginx:
    build: ./requirements/nginx
    container_name : nginx
    depends_on:
      - "wordpress"
    volumes:
      - wp-website:/var/www/html/wordpress
    image: inception/nginx
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
      
  wordpress:
    build: 
      context: ./requirements/wordpress
      args:
        DBNAME : ${DBNAME}
        USERNAME : ${USERNAME}
        DB_PASSWORD : ${DB_PASSWORD}
        WP_ADMIN_NAME : ${WP_ADMIN_NAME}
        WP_ADMIN_PASS : ${WP_ADMIN_PASS}
        WP_ADMIN_EMAIL : ${WP_ADMIN_EMAIL}
        WP_USER_NAME : ${WP_USER_NAME}
        WP_USER_PASS : ${WP_USER_PASS}
        WP_USER_EMAIL : ${WP_USER_EMAIL}
    container_name : wordpress
    depends_on:
      - "mariadb"
    volumes:
      - wp-website:/var/www/html/wordpress
    image: inception/wordpress
    networks:
      - inception
    restart: always

  mariadb:
    build: 
      context: ./requirements/mariadb
      args:
        DBNAME : ${DBNAME}
        USERNAME : ${USERNAME}
        DB_PASSWORD : ${DB_PASSWORD}
        ROOT_PASS: ${ROOT_PASS}
    container_name : mariadb
    volumes:
      - wp-database:/var/lib/mysql
    image: inception/mariadb
    networks:
      - inception
    restart: always

  
networks:
  inception:
    driver: bridge

volumes:
  wp-database:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/mysql

  wp-website:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/wp
