CREATE DATABASE IF NOT EXISTS DBNAME DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

GRANT ALL ON DBNAME.* TO 'USERNAME'@'localhost' IDENTIFIED BY 'DB_PASSWORD';
GRANT ALL ON DBNAME.* TO 'USERNAME'@'%' IDENTIFIED BY 'DB_PASSWORD';

FLUSH PRIVILEGES;

GRANT ALL ON DBNAME.* TO 'root'@'localhost' IDENTIFIED BY 'ROOT_PASS';
GRANT ALL ON DBNAME.* TO 'root'@'%' IDENTIFIED BY 'ROOT_PASS';

SET PASSWORD FOR 'root'@'localhost' = PASSWORD('ROOT_PASS');
SET PASSWORD FOR 'root'@'%' = PASSWORD('ROOT_PASS');
